/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kynake.discord.bot;

import java.nio.file.Files;
import java.nio.file.Paths;

import net.dv8tion.jda.api.*;
import net.dv8tion.jda.api.requests.GatewayIntent;

import javax.security.auth.login.LoginException;

import kynake.discord.bot.handlers.CommandHandler;

import java.io.IOException;

public class TestBot {
    public static JDA jda;

    public String getVersion() {
        return System.getProperty("java.version");
    }

    public static void main(String[] args) throws IOException, LoginException {
        System.out.println("Java version: " + new TestBot().getVersion());

        // Get Token
        String token = new String(Files.readAllBytes(Paths.get("token.txt")));


        // Create API Instance
        jda = JDABuilder.create(token, GatewayIntent.GUILD_MESSAGES, GatewayIntent.GUILD_VOICE_STATES).build();
        try {
            jda.awaitReady();
        } catch(InterruptedException | IllegalStateException e) {
            System.err.println("Connection to Discord via JDA failed");
            e.printStackTrace();
        }

        // Register API Event Handlers
        jda.addEventListener(new CommandHandler());

    }
}
