/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kynake.discord.bot;

public class TestBot {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new TestBot().getGreeting());
    }
}
