/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kynake.discord.bot;

import org.junit.Test;
import static org.junit.Assert.*;

public class TestBotTest {
    @Test public void testAppHasAGreeting() {
        TestBot classUnderTest = new TestBot();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
